# Generated by Django 4.2.2 on 2024-05-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_categories_created_products_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='definition',
            new_name='description',
        ),
        migrations.AddField(
            model_name='categories',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
