# Generated by Django 4.2.2 on 2024-05-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_rename_definition_products_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='image',
            new_name='image_path',
        ),
        migrations.AddField(
            model_name='categories',
            name='image_path',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
